export default {
  input: {
    maxFileSize: 50000000,
  },
  output: {
    filePath: "repomix-output.xml",
    style: "xml",
    parsableStyle: false,
    compress: false,
    fileSummary: true,
    directoryStructure: true,
    files: true,
    removeComments: false,
    removeEmptyLines: false,
    topFilesLength: 5,
    showLineNumbers: false,
    includeEmptyDirectories: true,
    truncateBase64: true,
    tokenCountTree: 50000,
    git: {
      sortByChanges: true,
      sortByChangesMaxCommits: 100,
      includeDiffs: true,
      includeLogs: true,
      includeLogsCount: 50,
    },
  },
  include: [],
  ignore: {
    useGitignore: true,
    useDefaultPatterns: true,
    customPatterns: [
      "__pycache__",
      "*.pyc",
      ".git",
      ".venv",
      ".hypothesis",
      "*.log",
      "CONTEXT.md",
      "CONVO.md",
      "TODO.md",
      "old",
      "un.egg-info",
      "verifiers",
      "proxy/target",
      "secret.nu",
      ".vscode",
      ".claude",
      "node_modules",
      ".next",
      "dist",
      "build",
    ],
  },
  security: {
    enableSecurityCheck: true,
  },
  tokenCount: {
    encoding: "o200k_base",
  },
};
